<?php

namespace app\admin\controller;
use app\common\model\Configure as M;
class Configure extends Base
{
    protected $m;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->m = new M();
    }

    /**
     * 显示资源列表
     *
     * @return \think\Response
     */
    public function index()
    {
        $list = $this->m->paginate();
        $this->assign('list', $list);
        return $this->fetch();
    }

    /**
     * 显示创建资源表单页.
     *
     * @return \think\Response
     */
    public function create()
    {
        return view('create');
    }

    /**
     * 保存新建的资源
     *
     * @param  \think\Request  $request
     * @return \think\Response
     */
    public function save()
    {
        $res = $this->m->add();
        return $res;
    }

    /**
     * 显示编辑资源表单页.
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function edit($id)
    {
        $data = $this->m->find($id);
        $this->assign('data', $data);
        return $this->fetch();
    }

    /**
     * 保存更新的资源
     *
     * @param  \think\Request  $request
     * @param  int  $id
     * @return \think\Response
     */
    public function update($id)
    {
        $m = new M();
        $res = $m->edit($id);
        return $res;
    }

    /**
     * 删除指定资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function delete($id)
    {
        $m = new M();
        $res = $m->delete($id);
        return $res;
    }

    /**
     * 更新状态
     *
     * @param $id
     * @return array
     */
    public function setStatus($id)
    {
        if(!$id){
            return toJson('数据不存在!');
        }
        $user = M::get($id);
        $user->status = $user->getData('status')?0:1;
        $user->save();
        return toJson(true, $user->status);
    }
}
