<?php

namespace app\admin\controller;

use app\common\model\Network as M;
use app\common\model\NetworkType as Type;
use app\common\model\Address;
class Network extends Base
{
    protected $m;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->m = new M();
    }

    /**
     * 显示资源列表
     *
     * @return \think\Response
     */
    public function index()
    {
        $list = $this->m->paginate();
        $this->assign('list', $list);
        return $this->fetch();
    }

    public function jiaqi(){
        $list = $this->m->where('type_id', 1)->paginate();
        $this->assign('list', $list);
        return $this->fetch('index');
    }

    /**
     * 显示创建资源表单页.
     *
     * @return \think\Response
     */
    public function create()
    {
        $type = new Type();
        $typeList = $type->where('status',1)->select();
        $addressList = Address::where('pid',0)->select();
        $this->assign('typeList', $typeList);
        $this->assign('addressList', $addressList);
        return $this->fetch();
    }

    /**
     * 保存新建的资源
     *
     * @param  \think\Request  $request
     * @return \think\Response
     */
    public function save()
    {
        $res = $this->m->add();
        return $res;
    }

    /**
     * 显示编辑资源表单页.
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function edit($id)
    {
        $data = $this->m->getById($id);
        $type = new Type();
        $typeList = $type->where('status',1)->select();
        $addressList = Address::where('pid',0)->select();
        $cityList = Address::where('pid',$data['province_id'])->select();
        $countyList = Address::where('pid',$data['city_id'])->select();
        $this->assign('typeList', $typeList);
        $this->assign('addressList', $addressList);
        $this->assign('cityList', $cityList);
        $this->assign('countyList', $countyList);
        $this->assign('data', $data);
        return $this->fetch();
    }

    /**
     * 保存更新的资源
     *
     * @param  \think\Request  $request
     * @param  int  $id
     * @return \think\Response
     */
    public function update($id)
    {
        $res = $this->m->edit($id);
        return $res;
    }

    /**
     * 删除指定资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function delete($id)
    {
        $res = $this->m->delete($id);
        return $res;
    }

    /**
     * 更新状态
     *
     * @param $id
     * @return array
     */
    public function setStatus($id)
    {
        if(!$id){
            return toJson('数据不存在!');
        }
        $user = M::get($id);
        $user->status = $user->getData('status')?0:1;
        $user->save();
        return toJson(true, $user->status);
    }

    public function type(){
        $type = new Type();
        $list = $type->getList([]);
        $this->assign('list', $list);
        return $this->fetch();
    }
}
