<?php
/**
 * Created by mumu.
 * Date: 2016/12/22
 * Time: 13:29
 */
namespace app\admin\controller;
use app\common\model\NetworkType as M;
class NetworkType extends Base
{
    protected $m;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->m = new M();
    }

    public function index(){
        $where = [];
        $list = $this->m->where($where)->paginate();
        $this->assign('list', $list);
        return $this->fetch();
    }

    public function setStatus($id)
    {
        if(!$id){
            return toJson('数据不存在!');
        }
        $type = M::get($id);
        $type->status = $type->getData('status')?0:1;
        $type->save();
        return toJson(true, $type->status);
    }
}